genre.php:
    sort: 1
    pages: 1
list.php:
    sort: 1
    pages: 1
grid.php:
    sort: 1
    pages: 1
test.php:
    sort: 0
    pages: 0
search.php:
    sort: 1
    pages: 1
genreEditor.php:
    sort: 1
    pages: 1
artistEditor.php:
    sort: 1
    pages: 1
dupes.php:
    sort: 1
    pages: 0
