home:
    url: home.php
    text: !php/const NavBar_Text_Home
    icon: fa-home
    studio: false
recent:
    url: recent.php?direction=ASC&sort=v.added
    text: !php/const NavBar_Text_Recent
    icon: fa-star
    studio: false
    dropdown:
        [
            {
                "1":
                    {
                        url: recent.php?direction=ASC&sort=v.added&days=1,
                        icon: fa-star,
                    },
                "2":
                    {
                        url: recent.php?direction=ASC&sort=v.added&days=2,
                        icon: fa-star,
                    },
                "4":
                    {
                        url: recent.php?direction=ASC&sort=v.added&days=4,
                        icon: fa-star,
                    },
                "5":
                    {
                        url: recent.php?direction=ASC&sort=v.added&days=5,
                        icon: fa-star,
                    },
            },
        ]
favorites:
    url: favorites.php
    text: !php/const NavBar_Text_Favorites
    icon: fa-heart
    studio: false
watch:
    url: video.php
    text: !php/const NavBar_Text_WatchFavorites
    icon: fa-play-circle
    studio: false
    js: { "Window": true }
list:
    url: list.php
    text: !php/const NavBar_Text_List
    icon: fa-list
    studio: true
grid:
    url: grid.php
    text: !php/const NavBar_Text_Grid
    icon: fa-th
    studio: true
# folder:
#     url: file.php
#     text: !php/const NavBar_Text_Filebrowser
#     icon: grid
#     studio: true
playlist:
    url: playlist.php
    text: !php/const NavBar_Text_Playist
    icon: fa-list-alt
    studio: false
tag:
    url: tags.php
    text: !php/const NavBar_Text_Tags
    icon: fa-tag
    studio: false
artist:
    url: artist.php
    text: !php/const NavBar_Text_Artists
    icon: fa-female
    studio: false
# search:
#     url: search.php
#     text: !php/const NavBar_Text_Search
#     icon: ""
#     studio: false
extra:
    text: "Settings"
    icon: fa-cog
    dropdown:
        [
            { Duplicates: { url: dupes.php, icon: fa-star }
            },
            {
                artistEditor: { url: Config/artistEditor.php, icon: "" },
                studioEditor: { url: Config/studioEditor.php, icon: "" },
                genreEditor: { url: Config/genreEditor.php, icon: "" },
            },
            {
                wordMap: { url: editor.php, icon: "" },
                plEdit: { url: pledit.php, icon: "" },
                "File Browser": { url: filebrowser.php, icon: "" },
                test: { url: test.php, icon: "" },
            },
            {
                refresh: { url: "process.php?action=refresh", icon: "" },
                "Export SQL": { url: "process.php?action=exportSql", icon: "" },

                settings: { url: settings.php, icon: fa-gear },
            },
        ]
