home:
    url: home.php
    text:  !php/const NavBar_Text_Home
    icon: fa-home
    studio: false
recent:
    url: recent.php?direction=ASC&sort=v.added
    text: !php/const NavBar_Text_Recent
    icon: fa-star
    studio: false
    days: true
favorites:
    url: favorites.php
    text: !php/const NavBar_Text_Favorites
    icon: fa-heart
    studio: false
watch:
    url: video.php
    text: !php/const NavBar_Text_WatchFavorites
    icon: fa-play-circle
    studio: false
    js: {"Window": true}
list:
    url: list.php
    text: !php/const NavBar_Text_List
    icon: fa-list
    studio: true
grid:
    url: grid.php
    text: !php/const NavBar_Text_Grid
    icon: fa-th
    studio: true
# folder:
#     url: file.php
#     text: !php/const NavBar_Text_Filebrowser
#     icon: grid
#     studio: true
playlist:
    url: playlist.php
    text: !php/const NavBar_Text_Playist
    icon:  fa-list-alt
    studio: false
tag:
    url: tags.php
    text: !php/const NavBar_Text_Tags
    icon: fa-tag
    studio: false
artist:
    url: artist.php
    text: !php/const NavBar_Text_Artists
    icon: fa-female
    studio: false
# search:
#     url: search.php
#     text: !php/const NavBar_Text_Search
#     icon: ""
#     studio: false
extra:
    text: "Settings"
    icon: fa-cog
    dropdown: [{
            Duplicates: dupes.php},
        {
            artistEditor: Config/artistEditor.php,
            studioEditor: Config/studioEditor.php,
            genreEditor: Config/genreEditor.php
        },
        {
            wordMap: editor.php,
            plEdit: pledit.php,
            "File Browser": filebrowser.php,
            test: test.php
        },
        {
            refresh: "process.php?action=refresh",
            settings: settings.php
        }
    ]

