default:
    PAGE_TITLE: "Default Page"
    NAVBAR: true
    ALPHA_SORT: false
    SHOW_RATING: false
    SHOW_THUMBNAILS: true
    USE_FILTER: false
    BOTTOM_NAV: true
    SHOW_SORT: false
    SHOW_PAGES: false
    GRID_VIEW: false
    # LIST_VIEW: false
    # VIDEOINFO: true
home:
    PAGE_TITLE: "Home Page"
    BOTTOM_NAV: false
favorites:
    PAGE_TITLE: "Favorites Page"
    BOTTOM_NAV: true
album:
artist:
    PAGE_TITLE: "Artist Selection"
file:
    PAGE_TITLE: "File Listing"
list:
    PAGE_TITLE: "List view"
    SHOW_SORT: true
    SHOW_PAGES: true
    ALPHA_SORT: true
    USE_FILTER: false
    SHOW_RATING: true

grid:
    PAGE_TITLE: "Grid View"
    SHOW_SORT: true
    SHOW_PAGES: true
    ALPHA_SORT: false
    SHOW_RATING: true
editor:
    PAGE_TITLE: "Wordmap Editor"
search:
    PAGE_TITLE: "Search"
    BOTTOM_NAV: true
    SHOW_SORT: true
    SHOW_PAGES: true
    SHOW_RATING: true

genre:
    PAGE_TITLE: "Genre Selection"
    BOTTOM_NAV: false

    # SHOW_SORT: true
playlist:
    PAGE_TITLE: "Playlist Selection"
    BOTTOM_NAV: false

recent:
    PAGE_TITLE: "Recent Videos"
    BOTTOM_NAV: true
    SHOW_SORT: true
    SHOW_PAGES: true
settings:
    PAGE_TITLE: "Settings Page"
    BOTTOM_NAV: false
test:
    PAGE_TITLE: "Test Page"
studio:
    PAGE_TITLE: "Studio Page"
    BOTTOM_NAV: false
tags:
    PAGE_TITLE: "Tags Page"
    BOTTOM_NAV: false
video:
    PAGE_TITLE: "Video Page"
    BOTTOM_NAV: false
    NAVBAR: false
    SHOW_RATING: true

videoinfo:
    PAGE_TITLE: "Video Page"
    BOTTOM_NAV: false
    NAVBAR: false
    SHOW_RATING: true

filebrowser:
    PAGE_TITLE: "File Browser"
    BOTTOM_NAV: false
process:
    SHOW_RATING: true
